# Generated by Django 3.1.3 on 2020-11-22 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20201122_1657'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Medicamento',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='medicamento',
            new_name='nombre_medicamento',
        ),
    ]
